name: Publish Draft

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  publish:
    environment: drafts

    env:
      CONTAINER_ENGINE: docker

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Deployment key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.DEPLOY_KEY }}" | base64 -d  > ~/.ssh/id_rsa

    - name: Extract branch name
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Publish site
      run: make publish
      env:
        TARGET_SYSTEM: ${{ vars.TARGET_SYSTEM }} # This should be user@host
        TARGET_PORT: ${{ vars.TARGET_PORT }}
        TARGET_DIR: ${{ vars.TARGET_DIR }}/${{ steps.extract_branch.outputs.branch }}
        PUBLISH_DRAFT: true
